routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index');

//Main Page
Route::get('/', 'PageController@home')->name('main.index');
Route::get("product/{name}/detail", "PageController@detail")->name("main.detail");

//Route Group Auth
Route::group(['middleware' => 'auth'], function () {

    //All Model Resource
    Route::resource('businesses', 'BusinessController');
    Route::resource('categories', 'CategoryController');
    Route::resource('countries', 'CountryController');
    Route::resource('invoices', 'InvoicesController');
    Route::resource('subCategories', 'SubCategoriesController');
    Route::resource('trades', 'TradeController');
    Route::resource('users', 'UserController');
    Route::resource('deliveryCharges', 'DeliveryChargeController');
    Route::resource('shippings', 'ShippingController');
    Route::resource('products', 'ProductController');
    Route::resource('companies', 'CompanyController');
    Route::resource('cities', 'CityController');

    //Product Company
    Route::get('/company/{company_id}/products', 'ProductController@showProductCompany')->name("products.showProductCompany");
    Route::get('/company/{company_id}/product/create', "ProductController@createProductCompany")->name("products.createProductCompany");
    Route::get('/company/{company_id}/product/{product_id}', 'ProductController@editProductCompany')->name("products.editProductCompany");

    //Cart
    Route::get('/products/addToCart/{id}', 'ProductController@addToCart')->name('products.addToCart');
    Route::get('/cart/', "ProductController@getCart")->name('products.cart');
    Route::get('/cart/increase/{id}', "ProductController@increaseItemInCart")->name('increase.item');
    Route::get('/cart/decrease/{id}', "ProductController@decreaseItemInCart")->name('decrease.item');

    Route::group(['middleware' => 'CartChecker'], function () {

        //Checkout
        //Route::get('/checkout', "InvoicesController@Checkout")->name("invoice.checkout");
        Route::get('/checkout/{product_id}', "InvoicesController@checkout")->name("main.checkout");

    });
});

resources/views/main/checkout.blade.php
@extends('layouts.app_codebase')

@section('content')
    <div class="content">
        <div class="row">
            <div class="col-lg-6 offset-lg-3">
                <div class="block block-fx-shadow">
                    <ul class="nav nav-tabs nav-tabs-block nav-justified" data-toggle="tabs" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" href="#crypto-buy">Checkout</a>
                        </li>
                    </ul>
                    <div class="block-content tab-content">
                        <div class="tab-pane active" id="crypto-buy">
                            <form action="{{ route("invoices.store") }}" method="post">
                                @csrf
                                <div class="form-group row">
                                    <label class="col-4" for="crypto-buy-to">Delivery Location</label>
                                    <div class="col-4">
                                        {!! Form::select('delivery', $deliveries , ["walla"=>"Select One"] , ['class' => 'form-control',"onchange"=>"deliveryPicker(this.value)"]) !!}
                                    </div>
                                    <div class="col-4">
                                        {!! Form::select('delivery', $deliveryPrices , ["walla"=>"Select One"] , ['class' => 'form-control',"disabled"=>"","style"=>"-webkit-appearance: none;","id"=>"deliveryPrices" ]) !!}
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-4" for="crypto-buy-to">Shipping Method</label>
                                    <div class="col-4">
                                        {!! Form::select('shipping', $shippings , null , ['class' => 'form-control',"onchange"=>"shippingPicker(this.value)"]) !!}
                                    </div>
                                    <div class="col-4">
                                        {!! Form::select('shipping', $shippingPrices , null , ['class' => 'form-control',"disabled"=>"","style"=>"-webkit-appearance: none;","id"=>"shippingPrices"]) !!}
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-12" for="crypto-buy-from">Buy From</label>
                                    <div class="col-12">
                                        <div class="table-responsive">
                                            <table class="table" id="products-table">
                                                <thead>
                                                <tr>
                                                    <th>Detail</th>
                                                    <th>Quantity</th>
                                                    <th>Price</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                <tr>
                                                    <td>
                                                        {{$cartItem["products"][$product->id]["product"]->name}}
                                                    </td>
                                                    <td>
                                                        {{ $cartItem["products"][$product->id]["subTotalQuantity"] }}
                                                    </td>
                                                    <td id="productPrice">
                                                        {{ $cartItem["products"][$product->id]["subTotalPrice"] }}
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td id="deliveryLocationName">
                                                        Delivery Service
                                                    </td>
                                                    <td id="deliveryLocationQuantity">
                                                    </td>
                                                    <td id="deliveryLocationPrice">
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td id="shippingName">
                                                        Shipping Service
                                                    </td>
                                                    <td id="shippingQuantity">
                                                    </td>
                                                    <td id="shippingPrice">
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>Total</td>
                                                    <td></td>
                                                    <td>
                                                        <span id="total">
                                                            {{ $cartItem["products"][$product->id]["subTotalPrice"] }}
                                                        </span>
                                                        <input type="hidden" id="totalPrice" name="total" value="">
                                                        <input type="hidden" name="Buyer" value="{{ Auth::user()->id }}">
                                                        <input type="hidden" name="Seller" value="{{ $product->Companies_id }}">
                                                        <input type="hidden" name="product" value="{{ $cartItem["products"][$product->id]["product"]->id }}">
                                                    </td>
                                                </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <hr>
                                <hr>
                                <div class="form-group row">
                                    <div class="col-12">
                                        <button type="submit" class="btn btn-hero btn-lg btn-block btn-alt-primary">
                                            Checkout
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection

@section('javascript')
    <script type="text/javascript">
        var praductPrice = document.getElementById("totalProduct").innerHTML;
        document.getElementById("total").innerHTML = productPrice;

        function deliveryPicker(id) {
            document.getElementById("deliveryPrices").selectedIndex = id;
            var selected = document.getElementById("deliveryPrices");
            var price = selected.options[selected.selectedIndex].text;
            document.getElementById("deliveryLocationPrice").innerHTML = price;
            trans(price);
        };

        function shippingPicker(id){
            document.getElementById("shippingPrices").selectedIndex = id;
            var selected = document.getElementById("shippingPrices");
            var price = selected.options[selected.selectedIndex].text;
            document.getElementById("shippingPrice").innerHTML = price;
            trans(price);
        };
        
        function trans(price) {
            var total = document.getElementById("total").innerHTML;
            total = parseInt(total);
            price = parseInt(price);
            total = total + price;
            document.getElementById("total").innerHTML = total.toString();
            document.getElementById("totalPrice").value = total;
            
        }
    </script>
@endsection

resources/views/main/description.blade.php
@extends('layouts.app_codebase')

@section('content')
    <div class="content">
        <div class="my-50 text-center">
            <h2 class="font-w700 text-black mb-10">
                {{ $product->name }}
            </h2>
            <h3 class="h5 text-muted mb-0">
                <i class="fa fa-building mr-5"></i> {{ $product->companies->name }}
            </h3>
        </div>
        <div class="block block-rounded block-fx-shadow">
            <div class="block-content p-0 bg-image" style="background-image: url('{{ asset('uploads/product/'.$product->avatar) }}');">
                <div class="px-20 py-150 bg-black-op text-center rounded-top">
                    <h5 class="font-size-h1 font-w300 text-white mb-10">Rp. {{ number_format($product->price,2,",",".") }}</h5>
                </div>
            </div>
            <div class="block-content block-content-full">
                <div class="row">
                    <div class="col-md-12 order-md-1 py-20">
                        <p>{{$product->description  }}</p>
                    </div>
                </div>
            </div>
            <div class="block-content block-content-full border-top clearfix">
                <a class="btn btn-hero btn-alt-success float-right" href="{{ Auth::user()?route('products.addToCart',[$product->id]):url('/login') }}">
                    <i class="fa fa-cart-plus"></i>
                </a>
                <a class="btn btn-hero btn-alt-primary" href="{!! url()->previous() !!}">
                    <i class="fa fa-arrow-left"></i> Back
                </a>
            </div>
        </div>
    </div>
@endsection

resources/views/main/index.blade.php
@extends('layouts.app_codebase')

@section('content')
    <div class="block block-rounded block-transparent bg-image bg-image-bottom"
         style="background-image: url('{{ asset('/media/photos/photo13@2x.jpg') }}');">
        <div class="block-content bg-white-op">
            <div class="py-20 text-center">
                <h1 class="font-w700 mb-10">Many option to Choose</h1>
                {{--                <h2 class="h4 font-w400 text-muted">Hey Admin, create something amazing!</h2>--}}
            </div>
        </div>
    </div>
    <!-- END Hero -->

    <!-- Dummy content -->
    {{--    <div class="card-deck">--}}
    {{--        @foreach($products as $product)--}}
    {{--            <div class="card" style="width:400px">--}}
    {{--                <img src="{{ asset('uploads/product/'.$product->avatar) }}" class="card-img-top border-black-op-b"--}}
    {{--                     alt="...">--}}
    {{--                <div class="card-body">--}}
    {{--                    <h5 class="card-title">{{ $product->name }}</h5>--}}
    {{--                    <p class="card-text">{{ $product->description }}</p>--}}
    {{--                    <a href="{{ Auth::user()?route('products.addToCart',[$product->id]):url('/login') }}"--}}
    {{--                       class="btn btn-success btn-xs"--}}
    {{--                       title="Add to Cart"><i class="fa fa-cart-plus"></i></a>--}}
    {{--                    <a href="#" class="btn btn-outline-secondary" disabled="">{{ 'Rp. '.$product->price }}</a>--}}
    {{--                </div>--}}
    {{--            </div>--}}
    {{--        @endforeach--}}
    {{--    </div>--}}
    <div class="row">
        @foreach ($products as $product)
            <div class="col-md-6 col-xl-4">
                <!-- Property -->
                <div class="block block-rounded">
                    <div class="block-content p-0 overflow-hidden">
                        <a class="img-link" href="{{ route("main.detail",$product->name) }}">
                            <img class="img-fluid rounded-top" src="{{ asset('uploads/product/'.$product->avatar) }}"
                                 alt="">
                        </a>
                    </div>
                    <div class="block-content border-bottom">
                        <h4 class="font-size-h5 mb-10">{{ $product->name }}</h4>
                        <h5 class="font-size-h1 font-w300 mb-5">Rp. {{ number_format($product->price,2,",",".") }}</h5>
                        <p class="text-muted">
                            <i class="fa fa-building"></i> {{ $product->companies->name }}
                        </p>
                    </div>
                    <div class="block-content block-content-full">
                        <div class="row">
                            <div class="col-12">
                                <a href="{{ Auth::user()?route('products.addToCart',[$product->id]):url('/login') }}"
                                                       class="btn btn-success btn-sm btn-hero btn-noborder btn-block"
                                                       title="Add to Cart"><i class="fa fa-cart-plus"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- END Property -->
            </div>
        @endforeach
    </div>
    <!-- END Dummy content -->
@endsection